# SOPS configuration for secrets management
# Documentation: https://github.com/Mic92/sops-nix

keys:
  # User keys - can decrypt secrets on any machine
  - &user_sheva age1v3akezh6scntlpkej7c9jxjz42wasr0qlf5qgckga769nfhu4vtq3vtus9

  # Host keys - each machine has its own unique key
  # Generate with: sudo mkdir -p /var/lib/sops-nix && sudo age-keygen -o /var/lib/sops-nix/key.txt
  # View public key: sudo age-keygen -y /var/lib/sops-nix/key.txt
  - &host_simos age1akfcxcty6ycqh47lm6mzrmgf0d5y75urhhr9q2erwunjm5unepnst0k079
  # Uncomment these after generating keys on each host:
  - &host_athanasiou age12ge2msc4ltj4t5tr4rzhcylysun29tude7szm8gc30c42cwykqps3n5st9
  # - &host_kaleipo age1...

creation_rules:
  # Common secrets (accessible by all hosts + user key)
  # All secrets are stored in secrets/common/ and accessible by all configured hosts
  - path_regex: secrets/common/.*\.yaml$
    key_groups:
      - age:
        - *user_sheva
        - *host_simos
        - *host_athanasiou
        # - *host_kaleipo  # Uncomment after generating key on kaleipo
