{
    imports = [
        ./git.nix
        ./fzf.nix
        ./zsh.nix
        ./starship.nix
        ./terminal.nix
        ./go.nix
        ./kube.nix
        ./docker.nix
        ./hyprland.nix
        ./hyprland-theme.nix
        ./swww.nix
        ./wlogout.nix
        ./eww.nix
        ./vscode-plugins.nix
        ./neovim.nix
    ];
}